### ISSUE TITLE
'queued' parameter clarification

### ISSUE THREAD

**Issue by PlkMarudny** [ArthurClemens/dialogic#12]
I am trying to understand the 'queued' parameter, looking at the Svelete version demo, I tried to queue (or not) notifications, here is the code sample:

```
    <button
		class="ui button primary"
		on:click={() => {
			notification.show({
				dialogic: {
					component: NotificationComponent,
					className: "notification",
					queued: false,
					timeout: 6000
				}
			})
		}}>
		Add notification
    </button>
```

But in both cases notifications are queued somehow - is this because they occupy the same position? What would be the way to stack them on screen as they come eventually?

**Comment by ArthurClemens** [comment]
You are heading in the right direction, but there is one property missing. To show multiple notifications (or dialogs) in the same area (a container, or the page), they need to be distinguished by `id`.

Without that property, a default `id` value will be used, and that would be the same for all notifications.

For showing multiple notifications you could simply add a incrementing value:

```js
let id = 0;

// ...
notification.show({
  dialogic: {
    component: NotificationComponent,
    className: 'notification',
    queued: false,
    timeout: 6000,
    id: id++, // <======================
  },
});
```

A couple of tweaks to the demo:


1) Wrap `<Notification />` inside a container to it can contain a stack of notification elements:

```jsx
<div class="notification-container">
  <Notification />
</div>
```

2) Move this div inside the page div, because page has a height of the window.

3) Add to `styles.css`:

```css
.notification-container {
  display: flex;
  flex-direction: column;
  height: 100%;
}
.notification-container .mdc-snackbar {
  position: static;
}
```

That should bring you a step closer to your goal.

**Comment by PlkMarudny** [comment]
Indeed, this works, thank you very much.
